//create profile
export const CREATE_PROFILE_REQUEST="CREATE_PROFILE_REQUEST"
export const CREATE_PROFILE_SUCCESS="CREATE_PROFILE_SUCCESS"
export const CREATE_PROFILE_FAIL="CREATE_PROFILE_FAIL"
export const CREATE_PROFILE_RESET="CREATE_PROFILE_RESET"

//get profiles
export const GET_ALL_PROFILE_REQUEST="GET_ALL_PROFILE_REQUEST"
export const GET_ALL_PROFILE_SUCCESS="GET_ALL_PROFILE_SUCCESS"
export const GET_ALL_PROFILE_FAIL="GET_ALL_PROFILE_FAIL"

//get  profiles details
export const GET_DETAILS_REQUEST="GET_DETAILS_REQUEST"
export const GET_DETAILS_SUCCESS="GET_DETAILS_SUCCESS"
export const GET_DETAILS_FAIL="GET_DETAILS_FAIL"

//get User profiles details
export const USER_PROFILE_REQUEST="USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS="USER_PROFILE_SUCCESS"
export const USER_PROFILE_FAIL="USER_PROFILE_FAIL"

//del profile
export const DELETE_PROFILE_REQUEST="DELETE_PROFILE_REQUEST"
export const DELETE_PROFILE_SUCCESS="DELETE_PROFILE_SUCCESS"
export const DELETE_PROFILE_FAIL="DELETE_PROFILE_FAIL"
export const DELETE_PROFILE_RESET="DELETE_PROFILE_RESET"

//create profile
export const CREATE_EXPRIENCE_REQUEST="CREATE_EXPRIENCE_REQUEST"
export const CREATE_EXPRIENCE_SUCCESS="CREATE_EXPRIENCE_SUCCESS"
export const CREATE_EXPRIENCE_FAIL="CREATE_EXPRIENCE_FAIL"
export const CREATE_EXPRIENCE_RESET="CREATE_EXPRIENCE_RESET"

//del profile
export const DELETE_EXPRIENCE_REQUEST="DELETE_EXPRIENCE_REQUEST"
export const DELETE_EXPRIENCE_SUCCESS="DELETE_EXPRIENCE_SUCCESS"
export const DELETE_EXPRIENCE_FAIL="DELETE_EXPRIENCE_FAIL"
export const DELETE_EXPRIENCE_RESET="DELETE_EXPRIENCE_RESET"

//create profile
export const CREATE_EDUCATION_REQUEST="CREATE_EDUCATION_REQUEST"
export const CREATE_EDUCATION_SUCCESS="CREATE_EDUCATION_SUCCESS"
export const CREATE_EDUCATION_FAIL="CREATE_EDUCATION_FAIL"
export const CREATE_EDUCATION_RESET="CREATE_EDUCATION_RESET"

//del profile
export const DELETE_EDUCATION_REQUEST="DELETE_EDUCATION_REQUEST"
export const DELETE_EDUCATION_SUCCESS="DELETE_EDUCATION_SUCCESS"
export const DELETE_EDUCATION_FAIL="DELETE_EDUCATION_FAIL"
export const DELETE_EDUCATION_RESET="DELETE_EDUCATION_RESET"

//for error handle
export const CLEAR_ERRORS="CLEAR_ERRORS"